version: 3

vars:
  COMMIT_HASH: { sh: git log -n1 --format=%h }
  DATE: '{{now | date "2006-01-02T15:04:05Z07:00"}}'

tasks:
  lint:shell:
    set: [e,u,pipefail]
    status:
      - test -z "{{.SHELL_FILES}}"
    cmds:
      - task: docker:run
        vars:
          IMAGE: koalaman/shellcheck:stable
          CMD: -x {{.SHELL_FILES}}
    vars:
      SHELL_FILES:
        sh: >
          bash -c "while read -r f; do
            [[ -d \$f ]] && continue;
            if head -n1 \"\$f\" | grep -Eq '^#!(.*/|.*env +)(sh|bash|ksh)'; then
              printf \"\$f \";
            fi;
          done< <(git ls-files)"

  lint:go:
    cmds:
      - task: docker:run
        vars:
          IMAGE: golangci/golangci-lint:latest
          CMD: golangci-lint run ./...

  docker:run:
    internal: true
    set: [e,u,pipefail]
    cmds:
      - docker run -t {{.RM}} {{.PWD_MOUNT}} {{.FLAGS}} {{.IMAGE}} {{.CMD}}
    vars:
      PWD_MOUNT: '{{ternary "-v $PWD:$PWD -w $PWD" "" (eq (default "true" .PWD_MOUNT) "true")}}'
      RM: '{{ternary "--rm" "" (eq (default "true" .RM) "true")}}'
      FLAGS: '{{default "" .FLAGS}}'

  docker:build:
    internal: true
    run: when_changed
    set: [e,u,pipefail]
    dir: '{{.DIR}}'
    cmds:
      - docker build --file {{.DOCKER_FILE}} -t {{.IMAGE_NAME}} .
    vars:
      DOCKER_FILE: '{{default "Dockerfile" .DOCKER_FILE}}'
      DIR: '{{default "." .DIR}}'
